FROM jenkins/jenkins:lts
MAINTAINER Orlando Hehl Rebelo dos Santos 
USER root
RUN apt-get update && apt-get install -y ksh
RUN curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz && tar xzvf docker-17.04.0-ce.tgz  && mv docker/docker /usr/local/bin && rm -r docker docker-17.04.0-ce.tgz

