FROM node:latest
MAINTAINER Orlando Hehl Rebelo dos Santos
RUN apt-get update 
RUN apt-get update && apt-get install -y lsof vim-tiny
ENV APP_ENV=DEV
#RUN npm init
RUN npm install express
RUN npm install express-load
RUN npm install ejs
RUN npm install mysql
RUN npm install body-parser
RUN npm install -g nodemon
EXPOSE 3000
